# Generated by Django 3.2.4 on 2021-06-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MixWebShop', '0005_auto_20210629_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuser',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='basicuser',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='BasicUser',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
