# Generated by Django 3.2.4 on 2021-06-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixWebShop', '0006_auto_20210630_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
