# Generated by Django 3.2.4 on 2021-06-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixWebShop', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
