# Generated by Django 3.2.4 on 2021-06-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixWebShop', '0008_auto_20210630_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.AutoField(default=enumerate, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
